### ISSUE TITLE
crate db docker container crashes

### ISSUE THREAD

**Issue by utkarshmankad** [Fiware/tutorials.Time-Series-Data#30]
I tried running './service start' command from the main directory to run the services. However, I observed that the Crate DB image crashes almost immediately.
Things I tried to sort out - 
1. Changed image tag to latest
2. Removed the command section to see if the image runs correctly or not.
3. Changed image tag to previously stable version.
However, it is observed that the Crate DB image runs correctly in stand alone. Please help me sort out the issue.
Thanks and Regards

**Comment by jason-fox** [comment]
I just pulled and ran as follows - I can see no errors:

```console
 git status
```
```text
On branch NGSI-v2
Your branch is up to date with 'origin/NGSI-v2'.

nothing to commit, working tree clean
```
```console
 git rev-parse HEAD 
```
```text
678bed961be0069db4a5b64beca10dd2e29d62f1
```

Check that you have the right git hash, then pull the containers:

```console
./services create
```

```text
Pulling Docker images
Pulling mongo-db    ... done
Pulling iot-agent   ... done
Pulling orion       ... done
Pulling crate-db    ... done
Pulling quantumleap ... done
Pulling tutorial    ... done
Pulling grafana     ... done
```
Now start:

```console
 ./services start 
```
```text
Stopping containers
Starting seven containers Orion, QuantumLeap, IoT-Agent, Tutorial, a Grafana metrics dashboard and CrateDB and MongoDB databases.
- Orion is the context broker
- QuantumLeap will write to CrateDB
- Grafana will read from CrateDB
- IoT-Agent is configured for the UltraLight Protocol
- Tutorial acts as a series of dummy IoT Sensors over HTTP

Creating db-mongo ... done
Creating db-crate         ... done
Creating fiware-iot-agent   ... done
Creating fiware-orion       ... done
Creating fiware-quantumleap ... done
Creating grafana            ... done
Creating fiware-tutorial    ... done
Adding appropriate MongoDB indexes for Orion  ... done
Adding appropriate MongoDB indexes for IoT-Agent  ... done

⏳ Waiting for Orion to be available

⏳ Loading context data  done

⏳ Waiting for IoT-Agent to be available

IoT Agent HTTP state:  000  (waiting for 200)
⏳ Provisioning IoT devices  done
```
```text
NAMES                STATUS                             PORTS
fiware-tutorial      Up 17 seconds (health: starting)   0.0.0.0:3000-3001->3000-3001/tcp
fiware-quantumleap   Up 19 seconds (health: starting)   0.0.0.0:8668->8668/tcp
fiware-iot-agent     Up 19 seconds (health: starting)   0.0.0.0:4041->4041/tcp, 0.0.0.0:7896->7896/tcp, 4061/tcp
fiware-orion         Up 19 seconds (health: starting)   0.0.0.0:1026->1026/tcp

Now open http://localhost:3000/device/monitor
```

When running these statements the docker containers are starting fine for me.

To diagnose further you'll need to post a log from the failing docker container. e.g. `docker logs db-crate`

**Comment by jason-fox** [comment]
Also, sometimes docker needs clean up to work, try:

```console
docker system prune
docker network prune
docker volume prune
```

to free up resources.

**Comment by utkarshmankad** [comment]
I followed the instructions as per your answer. Everything goes fine as shown....

However, when I try to insert time-series data into Crate DB, (QuantumLeap API - List the first N Sampled Values - https://github.com/FIWARE/tutorials.Time-Series-Data#quantumleap-api---list-the-first-n-sampled-values). 

The request returns the error -
```"Something went wrong with QL. Error: No more Servers available, exception from last server: HTTPConnectionPool(host='crate-db', port=4200): Max retries exceeded with url: /_sql?error_trace=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d99f222b0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))"```

Then when I saw the running containers 
`docker ps -a`

Then I found that the Crate DB crashed - 
```bash
CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS                             PORTS                                                      NAMES
60a26b8307be        fiware/tutorials.context-provider   "/nodejs/bin/node ./…"   17 seconds ago      Up 16 seconds (health: starting)   0.0.0.0:3000-3001->3000-3001/tcp                           fiware-tutorial
49e25d830dd6        smartsdk/quantumleap:0.7.6          "/bin/sh -c 'python …"   18 seconds ago      Up 16 seconds (health: starting)   0.0.0.0:8668->8668/tcp                                     fiware-quantumleap
f100670d221e        grafana/grafana:6.1.6               "/run.sh"                18 seconds ago      Up 16 seconds                      0.0.0.0:3003->3000/tcp                                     grafana
4e2ba6836fe1        fiware/orion:2.4.2                  "/usr/bin/contextBro…"   18 seconds ago      Up 17 seconds (health: starting)   0.0.0.0:1026->1026/tcp                                     fiware-orion
7da6d403a80a        fiware/iotagent-ul:1.14.0           "docker/entrypoint.s…"   18 seconds ago      Up 17 seconds (health: starting)   0.0.0.0:4041->4041/tcp, 0.0.0.0:7896->7896/tcp, 4061/tcp   fiware-iot-agent
d4fcbd8e5690        mongo:3.6                           "docker-entrypoint.s…"   19 seconds ago      Up 18 seconds (health: starting)   0.0.0.0:27017->27017/tcp                                   db-mongo
f37a7e509f4c        crate:3.1.2                         "/docker-entrypoint.…"   19 seconds ago      Exited (78) 5 seconds ago                                                                     db-crate
```
Thus the container is created, but its crashing immediately.
PS : I did docker prune network, system and volume before proceeding. Still the error persists.

Please help me out. Thanks

**Comment by jason-fox** [comment]
Well, that QuantumLeap response error message looks fine, because there is no CrateDB running. :smile: 

Since CrateDB is failing for you,  you'll need to diagnose the log from the failing docker container. e.g. `docker logs db-crate`. However that would be a [Crate-DB error](https://stackoverflow.com/questions/tagged/cratedb), not a tutorial failure.

**Comment by utkarshmankad** [comment]
Figured out the issue from the logs 
```
ERROR: [1] bootstrap checks failed
[1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]

```
sorted out the by using the command - 

```
sudo sysctl -w vm.max_map_count=262144
```
Closing the issue here. 
Thanks a lot 👍 :)

**Comment by amotl** [comment]
Dear Utkarsh and Jason,

thanks for sharing this. https://github.com/crate/crate/issues/6293, https://github.com/crate/crate/issues/8227, https://github.com/crate/crate/issues/8338 and https://github.com/crate/crate/issues/8930 talk about the same issue.

Unfortunately, this setting has to be applied to the **host system**, so there is no way to fix that within the Docker container itself. Others have been struggling with this as well, see for example https://github.com/docker-library/elasticsearch/issues/133, https://github.com/sonarsource/docker-sonarqube/issues/279 and https://github.com/docker/for-win/issues/5202.

The respective documentation for Elasticsearch and CrateDB can be found at [1] and [2]. If the limit cannot be adjusted on the host system, the memory map limit check can be bypassed by passing the `-Cnode.store.allow_mmapfs=false` option to the crate command as documented at [3]. However, this will result in degraded performance.

@jason-fox and @fisuda: Can I humbly suggest to put a short comment about this specific issue into the `README.md` and `README.ja.md` files and link to the respective documentation of CrateDB [2,3] in order to improve the experience for users not aware about these technical details?

Apart from that, I would like to suggest to add the `CRATE_HEAP_SIZE=2g` environment variable setting to the `crate-db` section within `docker-compose.yml`, see also [3].

With kind regards,
Andreas.

cc @seut

[1] https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_set_vm_max_map_count_to_at_least_262144
[2] https://crate.io/docs/crate/howtos/en/latest/admin/bootstrap-checks.html#bootstrap-checks
[3] https://crate.io/docs/crate/howtos/en/latest/deployment/containers/docker.html#troubleshooting
