### ISSUE TITLE
CrateDB InstanceID:

### ISSUE THREAD

**Issue by drypatrick** [Fiware/tutorials.Time-Series-Data#49]
Using the tutorial configuration, I discovered that the instance ID in the mt<FIWARE_SERVICE>.et<CONTEXTS_TYPE> table in CrateDB starts with `urn:ngsi-ld` which should be something related to the "ld" version of NGSI and not to the v2. Is this normal, or should the configuration of CrateDB be changed?

Query:
```
curl -iX POST \
	'http://localhost:4200/_sql' \
	-H 'Content-Type: application/json' \
	-d '{"stmt":"SELECT * FROM mtopcua_car.etdevice ORDER BY time_index ASC LIMIT 3"}'
```

Answer:
```
{
	"cols": ["entity_id", "entity_type", "time_index", "fiware_servicepath", "__original_ngsi_entity__", "instanceid", "second"],
"rows": [
			["age01_Car", "Device", 1659188768727, "/demo", null, "urn:ngsi-ld:ecd573d6-c3f2-468c-bc48-4900864e629a", "9"],
			["age01_Car", "Device", 1659188770684, "/demo", null, "urn:ngsi-ld:c3557961-38f3-4da3-ae9c-86bc7c8536d4", "10"],
			["age01_Car", "Device", 1659188771499, "/demo", null, "urn:ngsi-ld:f3ef4766-d971-47d3-9331-5f7f335e4d26", "12"]
	],
	"rowcount": 3,
	"duration": 4.069
}
```

**Comment by jason-fox** [comment]
Don't think that is an issue. The `instanceid` is a [URN](https://en.wikipedia.org/wiki/Uniform_Resource_Name) which is following the form

```text
urn:<namespace-identifier>:<namespace-specific-string >
```

Where the namespace identifier, and may include letters, digits, and the namespace-specific string may include ASCII letters and digits, and many punctuation and special characters.

According to the ETSI [NGSI-LD Specification](https://www.etsi.org/deliver/etsi_gs/CIM/001_099/009/01.05.01_60/gs_CIM009v010501p.pdf):

> ### A.3 NGSI-LD namespace
>
> NGSI-LD defines a specific URN [9] namespace intended to help API users to design readable, clean and simple
> identifiers. As it is based on URNs, the usage of this identification approach is not recommended when dereferenceable
> URIs are needed (fully-fledged linked data scenarios).
>
> The referred namespace is defined as follows (to be registered with IANA):
>  - Namespace identifier: NID = `ngsi-ld`
> -  Namespace specific string: NSS = EntityTypeName ":" EntityIdentificationString
>
> EntityTypeName shall be an Entity Type Name which can be expanded to a URI as per the `@context`. 

So it looks like `urn:ngsi-ld:...` is valid, particularly if it due to be registered with [IANA](https://www.iana.org/)

**Comment by drypatrick** [comment]
And this can not be changed? Because in my opinion those could generate some confusion between the tho version of NGSI

**Comment by jason-fox** [comment]
That would need to be a feature request for QuantumLeap itself - you should raise an issue [here](https://github.com/orchestracities/ngsi-timeseries-api/issues) - the tutorial is only reporting on the implementation as  currently is.
